config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'todos', to: 'todos#index'
  root 'todos#index'
  get 'todos/new'
  post 'todos', to: 'todos#create'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy', as: 'delete_todo'
  get 'todos/:id/complete', to: 'todos#complete', as: 'complete_todo'
  get 'lista', to: 'todos#list', as: 'list_todo' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end
  def new
    @todo = Todo.new
  end
  def create
    todo = Todo.new(todo_params)
    todo.save
    if todo.save
      redirect_to root_path, notice: 'Se creo con exito el ToDo!'
    else
      redirect_to todos_new_path, notice: 'No se pudo crear el ToDo!'
    end

  end
  def show
    @todo = Todo.find(params[:id])
  end
  def edit
    @todo = Todo.find(params[:id])
  end
  def update
    @todo = Todo.find(params[:id])
    if @todo.update(todo_params)
      redirect_to root_path, notice: 'Se ha actualizado con exito!'
    else
      redirect_to edit_todo_path(@todo), notice: 'No se ha podido actulizar!'
    end
  end
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to root_path, notice: 'Se ha Destruido!'
  end
  def complete
    @todo = Todo.find(params[:id])
    @todo.completed = true
    @todo.save
    redirect_to root_path
  end
  def list
    @todos = Todo.all
  end

  private

  def todo_params
    params.require(:todo).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp2</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Index', root_path, class:"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to 'Lista', list_todo_path, class:"nav-item nav-link" %>
          <%= link_to 'Crear ToDo', todos_new_path, class:"nav-item nav-link" %>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>Editando un ToDo</h1>
<%= form_with(model: @todo, local: true) do |form| %>
  <%= form.label :Descripcion %>
  <%= form.text_field :description %>
  <br>
  <%= form.label :Completado%>
  <%= form.check_box :completed %>
  <br>
  <%= form.submit 'Editar', class: 'btn btn-outline-primary' %>
<% end %>

app/views/todos/index.html.erb
<h1>Index</h1>
<% @todos.each do |t| %>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%="Descripcion: #{t.description} " %></h5>
      <% if t.completed %>
          <%= 'Esta: Completado' %>
          <% else %>
         <%= 'Esta: No Completado' %>
      <% end %>
      <br>
      <%= link_to 'Mostrar ToDo', todo_path(t), class: 'btn btn-outline-primary' %>
      <%= link_to 'Editar ToDo', edit_todo_path(t), class: 'btn btn-outline-primary' %>
      <%= link_to 'Eliminar', delete_todo_path(t), method: :delete, class: 'btn btn-outline-primary'  %>
      <%= link_to 'Completado', complete_todo_path(t), class: 'btn btn-outline-primary' %>
  </div>
</div>
<% end %>
<%= link_to 'Crear ToDo', todos_new_path, class: 'btn btn-outline-primary' %>
<%= link_to 'Lista ToDos', list_todo_path, class: 'btn btn-outline-primary' %>

app/views/todos/list.html.erb
<h2>Lista ToDos</h2>
<div class="row">
  <div class="col-6">
      <% @todos.each do |t|%>
        <% if !t.completed %>
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= t.description  %></h5>
               <% if t.completed %>
                   <%= 'Completado' %>
                   <% else %>
                  <%= 'No Completado' %>
               <% end %>
            </div>
          </div>
        <% end %>
    <% end %>
  </div>
    <div class="col-6">
      <% @todos.each do |t|%>
        <% if t.completed %>
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= t.description  %></h5>
               <% if t.completed %>
                   <%= 'Completado' %>
                   <% else %>
                  <%= 'No Completado' %>
               <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/todos/new.html.erb
<h1>Creacion nuevo Todo</h1>
<%= form_with(model: @todo, local: true) do |form| %>
  <%= form.label :descripcion %>
  <%= form.text_field :description %>
  <br>
  <%= form.submit 'Crear', class: 'btn btn-outline-primary' %>
<% end %>
<%= link_to 'Volver al Index', root_path, class: 'btn btn-outline-primary' %>

app/views/todos/show.html.erb
<h3>Detalles</h3>
<br>
<strong>Descripcion:</strong> <%= @todo.description%>
<strong>Completado:</strong> <%= @todo.completed %>
<br>
<%= link_to 'Volver al Index', root_path, class: 'btn btn-outline-primary' %>